server:
  port: 2100
spring:
  application:
    name: service-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

#Eureka 配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8260/eureka
  instance:
    prefer-ip-address: true

service-provider:
  ribbon:
    ConnectTimeout: 250 #单位ms,请求连接超时时间
    ReadTimeout: 1000 #单位ms,请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数

